In [1]:
import numpy as np
from sklearn.model_selection import cross_val_score, GridSearchCV
import pickle
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score


In [2]:
data = np.loadtxt("learn/mixture_data")
labels = np.loadtxt("learn/mixture_label")
# data=np.delete(data, [1, 4], 1)
scal = MinMaxScaler()
scal.fit_transform(data)


array([[ 0.51859956,  0.05428954,  0.02299656,  0.4726477 ,  0.0629317 ,
         0.02215099],
       [ 0.48796499,  0.04691689,  0.02042841,  0.56017505,  0.03069839,
         0.01373074],
       [ 0.76586433,  0.04691689,  0.02042841,  1.        ,  0.03069839,
         0.01373074],
       ..., 
       [ 0.20568928,  0.47184987,  0.48464951,  0.17067834,  0.56868764,
         0.36338628],
       [ 0.21006565,  0.46983914,  0.47332633,  0.1750547 ,  0.56868764,
         0.36671132],
       [ 0.39606127,  0.46983914,  0.47332633,  0.35229759,  0.56868764,
         0.36671132]])

In [8]:
from sklearn.svm import LinearSVC
reg = LinearSVC()
res = cross_val_score(reg, data, labels, n_jobs=4, verbose=3, cv=5, scoring="mean_accuracy")
reg.fit(data,labels)
print res

ValueError: 'mean_accuracy' is not a valid scoring value. Valid options are ['accuracy', 'adjusted_mutual_info_score', 'adjusted_rand_score', 'average_precision', 'completeness_score', 'explained_variance', 'f1', 'f1_macro', 'f1_micro', 'f1_samples', 'f1_weighted', 'fowlkes_mallows_score', 'homogeneity_score', 'mutual_info_score', 'neg_log_loss', 'neg_mean_absolute_error', 'neg_mean_squared_error', 'neg_mean_squared_log_error', 'neg_median_absolute_error', 'normalized_mutual_info_score', 'precision', 'precision_macro', 'precision_micro', 'precision_samples', 'precision_weighted', 'r2', 'recall', 'recall_macro', 'recall_micro', 'recall_samples', 'recall_weighted', 'roc_auc', 'v_measure_score']

In [4]:
from sklearn.neighbors import KNeighborsClassifier
reg = KNeighborsClassifier(n_neighbors=5)
res = cross_val_score(reg, data, labels, n_jobs=4)
print res


[ 0.67002012  0.66262626  0.62828283]


In [36]:
from sklearn.linear_model import SGDClassifier
reg = SGDClassifier()
res = cross_val_score(reg, data, labels, n_jobs=4)
print res

/home/maxence/anaconda3/envs/python2/lib/python2.7/site-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)


/home/maxence/anaconda3/envs/python2/lib/python2.7/site-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)


/home/maxence/anaconda3/envs/python2/lib/python2.7/site-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)


[ 0.56803845  0.56593572  0.56587051]


In [5]:
from sklearn.ensemble import GradientBoostingClassifier
reg = GradientBoostingClassifier ()
res = cross_val_score(reg, data, labels, scoring="accuracy", n_jobs=4, verbose=10, cv=10)
reg.fit(data, labels)
print(reg.score(data, labels))
print res

[CV]  ................................................................


[CV]  ................................................................


[CV]  ................................................................


[CV]  ................................................................


[CV] ........................... , score=0.673333333333, total=   0.2s


[CV] ........................... , score=0.846666666667, total=   0.2s


[CV]  ................................................................


[CV]  ................................................................


[CV] ........................... , score=0.885906040268, total=   0.2s


[CV] ........................... , score=0.773333333333, total=   0.2s


[CV]  ................................................................


[CV]  ................................................................


[CV] ........................... , score=0.635135135135, total=   0.1s


[CV]  ................................................................


[CV] ........................... , score=0.716216216216, total=   0.1s


[CV]  ................................................................


[CV] ........................... , score=0.932432432432, total=   0.3s


[CV] ............................ , score=0.72972972973, total=   0.2s


[Parallel(n_jobs=4)]: Done   5 out of  10 | elapsed:    0.4s remaining:    0.4s
[Parallel(n_jobs=4)]: Done   7 out of  10 | elapsed:    0.5s remaining:    0.2s


[CV] ........................... , score=0.662162162162, total=   0.3s


[CV] ........................... , score=0.648648648649, total=   0.2s


0.866173503699
[ 0.67333333  0.84666667  0.77333333  0.88590604  0.93243243  0.63513514
  0.66216216  0.72972973  0.71621622  0.64864865]


[Parallel(n_jobs=4)]: Done  10 out of  10 | elapsed:    0.7s finished


In [6]:
with open("learn/mixture_estimator", "w") as file:
    pickle.dump(reg, file)

In [7]:
with open("learn/scal", "w") as file:
    pickle.dump(scal, file)