In [7]:
import numpy as np
from sklearn.model_selection import cross_val_score, GridSearchCV
import pickle
from sklearn.metrics import accuracy_score


In [8]:
data = np.loadtxt("learn/data_traite_max_100")
labels = np.loadtxt("learn/label_max_100")

In [6]:
from sklearn.svm import LinearSVC
reg = LinearSVC()
res = cross_val_score(reg, data, labels, n_jobs=4, verbose=3)
#reg.fit(data,labels)
print res

[CV]  ................................................................


[CV]  ................................................................


[CV]  ................................................................


[CV] ........................... , score=0.992893711317, total=  29.4s


[CV] ........................... , score=0.996408558329, total=  29.6s


[CV] ........................... , score=0.995720835456, total=  30.4s


[0.99289371 0.99572084 0.99640856]


[Parallel(n_jobs=4)]: Done   3 out of   3 | elapsed:   30.6s finished


In [13]:
from sklearn.linear_model import SGDClassifier
reg = SGDClassifier()
res = cross_val_score(reg, data, labels, n_jobs=4)
print res

/home/maxence/anaconda3/envs/python2/lib/python2.7/site-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)


/home/maxence/anaconda3/envs/python2/lib/python2.7/site-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)


/home/maxence/anaconda3/envs/python2/lib/python2.7/site-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)


[0.99609027 0.99572084 0.9953515 ]


In [6]:
from sklearn.ensemble import RandomForestClassifier
reg = RandomForestClassifier(n_jobs=4)
reg.fit(data, labels)o
res = cross_val_score(reg, data, labels, scoring="accuracy")
print res


[0.994371   0.99508406 0.99502038]


In [9]:
from sklearn.ensemble import GradientBoostingClassifier
reg = GradientBoostingClassifier ()
res = cross_val_score(reg, data, labels, scoring="accuracy", n_jobs=4, verbose=10)
reg.fit(data, labels)
print res

[CV]  ................................................................


[CV]  ................................................................


[CV]  ................................................................


[CV] ........................... , score=0.995911869587, total=  21.2s


[CV] ........................... , score=0.994536563001, total=  21.5s


[CV] ........................... , score=0.996026490066, total=  21.6s


[Parallel(n_jobs=4)]: Done   3 out of   3 | elapsed:   21.7s remaining:    0.0s
[Parallel(n_jobs=4)]: Done   3 out of   3 | elapsed:   21.7s finished


[0.99453656 0.99602649 0.99591187]


In [8]:
from sklearn.linear_model import RidgeClassifier
reg = RidgeClassifier()
res = cross_val_score(reg, data, labels, n_jobs=4, verbose=10)
print res

[CV]  ................................................................


[CV]  ................................................................


[CV]  ................................................................


[CV] ........................... , score=0.980667838313, total=   0.1s


[CV] ........................... , score=0.991734589913, total=   0.2s


[CV] ........................... , score=0.974541518085, total=   0.2s


[Parallel(n_jobs=4)]: Batch computation too fast (0.1680s.) Setting batch_size=2.
[Parallel(n_jobs=4)]: Done   3 out of   3 | elapsed:    0.3s remaining:    0.0s
[Parallel(n_jobs=4)]: Done   3 out of   3 | elapsed:    0.3s finished


[0.98066784 0.99173459 0.97454152]


In [20]:
reg = RidgeClassifier()
param = {"normalize" : [True, False], "alpha" :[0.0001,0.001, 0.01, 0.1, 0.3],
         "fit_intercept" : [True, False]}
res = GridSearchCV(reg, param_grid=param, n_jobs=10)
res.fit(data, labels)
print(res.best_score_)

0.9886951206051909


In [25]:
from sklearn.ensemble import VotingClassifier
clas = VotingClassifier([("ridge", RidgeClassifier()), ("grad boost", GradientBoostingClassifier()), ("randForest", RandomForestClassifier()), ("svc", LinearSVC())])

In [26]:
res = cross_val_score(clas, data, labels, n_jobs=4, verbose=10)

print(res)

[CV]  ................................................................


[CV]  ................................................................


[CV]  ................................................................


/home/maxence/anaconda3/envs/python2/lib/python2.7/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[CV] ............................ , score=0.99630676753, total=  47.1s


/home/maxence/anaconda3/envs/python2/lib/python2.7/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[CV] ........................... , score=0.996332144677, total=  47.3s


/home/maxence/anaconda3/envs/python2/lib/python2.7/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[CV] ........................... , score=0.996370351503, total=  47.6s


[0.99630677 0.99633214 0.99637035]


[Parallel(n_jobs=4)]: Done   3 out of   3 | elapsed:   47.7s remaining:    0.0s
[Parallel(n_jobs=4)]: Done   3 out of   3 | elapsed:   47.7s finished


In [27]:
clas.fit(data, labels)


NameError: name 'pickle' is not defined

In [10]:
with open("learn/estimateur_grad_boost_max", "w") as file:
    pickle.dump(reg, file)

In [ ]:
d = data[0]
d = d.reshape(1, -1)
clas.predict(d)

ValueError: Expected 2D array, got 1D array instead:
array=[0. 0. 0. 0. 0. 0.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.