In [1]:
import numpy as np

In [114]:
M = np.zeros((15,19))
R = np.ones((15,1))*38

In [115]:
print(M)
print(R)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[38.]
 [38.]
 [38.]
 [38.]
 [38.]
 [38.]
 [38.]
 [38.]
 [38.]
 [38.]
 [38.]
 [38.]
 [38.]
 [38.]
 

In [116]:
coef = [(0,0),(0,1),(0,2),(1,3),(1,4),(1,5),(1,6),(2,7),(2,9),(2,10),(2,11),(2,8), (3,13),(3,14),(3,15),(3,12),(4,16),(4,17),(4,18)]
coef += [(5,0),(5,3),(5,7),(6,1),(6,4),(6,8),(6,12),(7,2),(7,5),(7,9),(7,13),(7,16),(8,6),(8,10),(8,14),(8,17),(9,11),(9,15),(9,15)]
coef += [(10,2),(10,6),(10,11),(11,1),(11,5),(11,10),(11,15),(12,0),(12,4),(12,9),(12,14),(12,18),(13,3),(13,8),(13,13),(13,17),(14,7),(14,12),(14,16)]
# coef += [(16,16)]
# coef += [(17,17)]
# coef += [(18,18)]
# coef += [(15,15)]

In [117]:
for i in coef:
    M[i] = 1

In [118]:
print(M)

[[1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1.]
 [1. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0.]]


In [119]:
I = np.linalg.inv(M)

LinAlgError: Last 2 dimensions of the array must be square

In [120]:
P = list(M)
for l in range(15):
    for c in range(l+1, 15):
        if(M[c,l] == 1):
            M[c,] -= M[l,]
            R[c] -= R[l]
print(M)
print(R)

[[ 1.  1.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.]
 [ 0.  0.  0.  1.  1.  1.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  1.  1.  1.  1.  0.  0.  0.  0.  0.  0.
   0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  1.  1.  1.  0.  0.
   0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  1.
   1.]
 [ 0. -1. -1.  1.  0.  0.  0.  1.  0.  0.  0.  0. -1. -1. -1. -1.  0.  0.
   0.]
 [ 0.  1.  0. -1.  0. -1. -1.  0.  1.  0.  0.  0.  1.  0.  0.  0.  0.  0.
   0.]
 [ 0.  1.  2. -1.  0.  1.  0. -2. -1.  0. -1. -1.  1.  2.  1.  1.  1.  0.
   0.]
 [ 0. -1.  0.  1.  0.  1.  2.  0. -1.  0.  1.  0. -1.  0.  1.  0.  0.  1.
   0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  1.  0.  0.
   0.]
 [ 0. -1.  1.  1.  0.  1.  2. -1. -2. -1. -1.  0. -1.  0.  0.  0.  0.  0.
   0.]
 [ 0.  2. -1. -2. -1. -1. -3.  1.  2.  1.  2.  0.  1.  0.  0.  1.  0.  0.
   0.]
 [ 0. -1. -1.  0.  1.  0.  0